groups:
- name: all
  jobs:
  - build-broker
  - build-tile
  - claim-pcf
  - deploy-tile
  - remove-tile
  - release-pcf

- name: manual
  jobs:
  - manual-release-pcf

resource_types:
  - name: gcs-resource
    type: docker-image
    source:
      repository: frodenas/gcs-resource

resources:
- name: version
  type: semver
  source:
    uri: git@github.com:cf-platform-eng/ms-sql-server-broker.git
    branch: version
    private_key: {{github-mssql-private-key}}
    file: version
    initial_version: 0.1.0
    driver: git

- name: pcf-environment
  type: pool
  source:
    branch: master
    pool: pcf1_10
    private_key: {{github-pool-private-key}}
    uri: git@github.com:cf-platform-eng/pipeline-resource-pool-v2

- name: tile-repo
  type: git
  source:
    branch: master
    uri: https://github.com/cf-platform-eng/ms-sql-server-broker

- name: broker-tile
  type: gcs-resource
  source:
    json_key: {{gcp_svc_acct_key}}
    bucket: {{gcp-bucket-name}}
    regexp: .*-(?P<version>.*)\.pivotal

- name: broker-jar
  type: gcs-resource
  source:
    json_key: {{gcp_svc_acct_key}}
    bucket: {{gcp-bucket-name}}
    regexp: .*-(?P<version>.*)\.jar

- name: tile-history
  type: gcs-resource
  source:
    json_key: {{gcp_svc_acct_key}}
    bucket: {{gcp-bucket-name}}
    regexp: tile-history-(?P<version>.*)\.yml

jobs:
- name: build-broker
  serial_groups: [version]
  plan:
  - get: tile-repo
    trigger: true
  - get: version
    params: {bump: patch}
  - task: build-broker
    file: tile-repo/sqlserver-broker/ci/build-broker/task.yml
  - put: broker-jar
    params: {file: broker-jar/*.jar}
  - put: version
    params: {file: version/number}

- name: build-tile
  serial_groups: [version]
  plan:
  - aggregate:
    - get: tile-repo
    - get: broker-jar
      passed:
        - build-broker
      trigger: true
    - get: version
    - get: tile-history
  - task: build-tile
    file: tile-repo/sqlserver-broker/ci/build-tile/task.yml
  - put: tile-history
    params: {file: tile-history-new/*.yml}
  - put: broker-tile
    params:
      file: broker-tile/*.pivotal

- name: claim-pcf
  serial_groups: [version]
  plan:
  - aggregate:
    - get: broker-tile
      trigger: true
      passed:
      - build-tile
  - put: pcf-environment
    params:
      acquire: true

- name: deploy-tile
  plan:
  - aggregate:
    - get: broker-tile
      passed:
      - claim-pcf
      trigger: true
    - get: pcf-environment
      passed:
      - claim-pcf
    - get: tile-repo
    - get: version
  - task: deploy-tile
    file: tile-repo/sqlserver-broker/ci/deploy-tile/task.yml
    on_failure:
      aggregate:
      - put: pcf-environment
        params:
          release: pcf-environment

- name: remove-tile
  plan:
  - aggregate:
    - get: tile-repo
    - get: broker-tile
    - get: pcf-environment
      passed:
        - deploy-tile
      trigger: true
  - task: remove-tile
    file: tile-repo/sqlserver-broker/ci/remove-tile/task.yml
    on_failure:
      aggregate:
      - put: pcf-environment
        params:
          release: pcf-environment

- name: release-pcf
  serial_groups: [version]
  plan:
  - get: pcf-environment
    passed:
    - remove-tile
    trigger: true
  - get: version
    params: {bump: final}
  - put: pcf-environment
    params:
      release: pcf-environment
  - put: version
    params: {file: version/number}

- name: manual-release-pcf
  plan:
  - get: pcf-environment
    passed:
    - claim-pcf
  - put: pcf-environment
    params:
      release: pcf-environment